"""initial

Revision ID: ab3873e54d3a
Revises: 
Create Date: 2025-06-04 14:51:17.140404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3873e54d3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('_alembic_tmp_sound')
    with op.batch_alter_table('sound', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sound_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sound', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sound_user_id',type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('_alembic_tmp_sound',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=200), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_sound_user')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
